### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by FiveKernelsMooncake** [Zyh716/TG_CRS_Code#1]
Hello,  I am very interested in your data set published on Coling2020. I have a few questions to ask. What do **key** and **value** respectively represent in **train_inter_history.pkl** file? Thank you. In addition, there seems to be a missing file corresponding to the movie and ID. Thank you

**Comment by Zyh716** [comment]
In the file train_inter_history.pkl, the key is generated by identity = str(conv_id) + '/' + str(message_id), the value is the interaction history of this conversation. 
     The file corresponding to the movie and ID named movies_with_mentions.csv had been published in  https://drive.google.com/drive/folders/14MBg4UfWwWL2nuTJtOmVL0QP9-zw_4hJ?usp=sharing , and  Zyh716/TG_CRS_Code (github.com) mentions it in Getting Started.  This was not included in the data link published earlier, and we will add it.
